### ISSUE TITLE
Issue with gcloud script

### ISSUE THREAD

**Issue by sagar-r-sonawane** [fabianlee/gcp-gke-clusters-ingress#1]
As is: `is_regional_cluster="${14:-0}"`
Should be: `is_regional_cluster="${13:-0}"`

Since we don't have 14 args in case of `privautopilot` menu choice.

**Comment by sagar-r-sonawane** [comment]
Thank you for the cool project, I tried to make it work using only TF but seems not working. Facing multiple issues partly due to the restrictions in my corp environment and gcp foundation.

**Comment by fabianlee** [comment]
thanks, is_regional_cluster parameter count now fixed.
